trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: flaskaksapp

steps:
- task: Docker@2
  inputs:
    containerRegistry: myflaskacr-sc
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      v1

- script: |
    kubectl apply -f k8s/deployment.yml
    kubectl apply -f k8s/service.yml
  displayName: 'Deploy to AKS'
